### ISSUE TITLE
Extension for interaction with 2 or more APis

### ISSUE THREAD

**Issue by MZAShelli** [diegomvh/angular-odata#10]
Idea to extend the libary to interact with 2 or more APIs.

**Comment by diegomvh** [comment]
Making correct use of the configuration it is possible to eventually pass to the module constructor more than one configuration, each with its own serviceRootUrl

```typescript
ODataModule.forRoot (ApiOneConfig, ApiTwoConfig, ApiThreeConfig ...)
```

For each resource that reaches the client, it can then be inferred to which configuration it belongs and thus solve what is related to that API

**Comment by diegomvh** [comment]
An example of how to configure more than one api
[AngularODataEntity](https://github.com/diegomvh/AngularODataEntity/blob/2f89e7cecdd5811a28b22569dc6c8546dd6a38df/src/app/app.module.ts#L37)

**Comment by MZAShelli** [comment]
Great, thank you very much, I'll take a look at that

Mit freundlichen Grüßen/ Best regards

 

 

M.  Seidert

MZA Meyer-Zweiradtechnik GmbH

Heckenweg 24

34246 Vellmar

 

Tel.: 0561/98200-1066

ms@mza-vertrieb.de

 

 

Von: Diego van Haaster [mailto:notifications@github.com] 
Gesendet: Freitag, 5. Juni 2020 00:55
An: diegomvh/angular-odata
Cc: MZA - Martin Seidert; Author
Betreff: Re: [diegomvh/angular-odata] Extension for interaction with 2 or more APis (#10)

 

An example of how to configure more than one api
AngularODataEntity <https://github.com/diegomvh/AngularODataEntity/blob/2f89e7cecdd5811a28b22569dc6c8546dd6a38df/src/app/app.module.ts#L37>
