### ISSUE TITLE
Issues with guid (latest version)

### ISSUE THREAD

**Issue by Bonny88** [diegomvh/angular-odata#11]
Hi Diego,

I see that you had closed some issues about the same topic, but it seems to me that is still not working as intended. I'll try to explain my scenario:

I have a service created using your automatic generator; the service expose an entity called "books" with a key called "id" of type edm.guid. When i try to get a single element (using either fetchOne or get) the url that the service compose is wrong:

![image](https://user-images.githubusercontent.com/34231909/83046379-388b5900-a047-11ea-931e-0db600f96958.png)

![image](https://user-images.githubusercontent.com/34231909/83046406-450fb180-a047-11ea-8954-0704d1794f8a.png)

WIth the help of our old friend, the chrome debugger, i found out that the key is passed to the builder method guid, which converts my string into an object with type "guid" and my value as the parameter "value".

![image](https://user-images.githubusercontent.com/34231909/83046640-96b83c00-a047-11ea-88c1-04b490c6766f.png)

![image](https://user-images.githubusercontent.com/34231909/83046703-a9cb0c00-a047-11ea-8098-82c3b0d51723.png)

Then, the method "buildQuery" is invoked, and when the key is checked the components of the object previously created are treated as two separate keys and not as a single key with a type specification:

![image](https://user-images.githubusercontent.com/34231909/83046927-ff071d80-a047-11ea-9aab-c4d0dd49b730.png)

Am i calling the function in the wrong way or is there an effective issue?

Thanks again for your efforts on this library.
Luca

**Comment by diegomvh** [comment]
Hi @Bonny88 

Thank you very much for reporting the problem with such good documentation.
The fix was already released in version 0.11.2

Regards

**Comment by Bonny88** [comment]
Hi Diego,

Thank you for the fast feedback, i can confirm that now all CRUD operations are being composed with the proper key.

Keep up the good work!
Luca
