### ISSUE TITLE
NullInjectorError: No provider for ODataService!

### ISSUE THREAD

**Issue by JoaoEdu93** [diegomvh/angular-odata#2]
Hi!

I have followed the steps described on README and I'm getting the error 'NullInjectorError: No provider for ODataService!'.
Can you help me, please?

Thanks

**Comment by diegomvh** [comment]
hi @JoaoEdu93 
many thanks for your issue report,
i forgot add the OData Service as a provider D'oh

Now is fixed.

... i think
