### ISSUE TITLE
Linking Entities by Reference

### ISSUE THREAD

**Issue by Norm-Cota** [diegomvh/angular-odata#21]
Hello,

I need to be able to be able to link two existing entities that are related in a many-to-many. As far as I can tell, the OData spec requires that you POST or PUT an OData Reference to the NavigationProperty (plus a "$ref"). I have the endpoint working on the server side (dotNet OData WebApi) but can't seem to find a way to create the request within angular-odata.

Here is a pseudo code example of what I am trying to do:

Given the following model/data:
- People: 
  - Schema: {ID: string, Locations: Location[]} 
  - Data: [{ID: "John"}]
- Location: 
  - Schema: {ID: string, People: []}
  - Data: [{ID: "London"}]

If I want to link "John" to the "London" location I would POST the following request:
```
POST http://odata.example.com/People('John')/Locations/$ref HTTP/1.1
<HTTP Headers here>

{"@odata.id":"http://odata.example.com/Locations('London')"}
```

This should create the link in the many-to-many table on the server. I have this working via Postman, but can't seem to figure out how to do it using angular-odata.

Am I missing how to create this request? Is this not currently supported? I appreciate any assistance.

**Comment by Norm-Cota** [comment]
Yep, posted too soon. Figured it out after taking a break and investigating the source more. Thanks for the awesome library!

For anyone who has the same question:

I am using the related generator project so the types that this example uses will only make sense in that context. In order to create the reference needed in the psuedo example above the call would be something like this:

```
this.peopleService
  .locations('John')  // This gets the 'Locations' Navigation Property for a specific Person with the ID of 'John'
  .reference()  // This gets the reference to the above. This is the bit that I missed earlier.
  .post(  // POST to create a new reference
    this.locationsService.entity('London')  // Give the entity that is the target of the new reference
  )
  .subscribe(result => console.log('Success!'));  // Win
```

**Comment by diegomvh** [comment]
Hi @Norm-Cota 

Thanks for giving the library a try.
Good to hear that the code generator is useful.
The truth is that there are many features in the library to date and very little documentation.
I trust the demo application to leave "documentation" but at some point it is difficult to leave all the characteristics and its different options reflected if it is not in plain colloquial language.

Here is an example of the references.

https://github.com/diegomvh/AngularODataEntity/blob/89ee9bcecfdc3975282f8b334994b7342fc01ecd/src/app/app.component.ts#L206

Regards
