### ISSUE TITLE
Enums not posting properly?

### ISSUE THREAD

**Issue by ISimplifyComplexity** [diegomvh/angular-odata#23]
Hi there, 

I'm using the Angular Generator project to create a client library. I initially thought that this was a problem with the generator but I'm now wondering if it's a problem with angular-odata?

We're having an issue with enums.

We have a user management system. Users can login using either windows or forms based Authentication. We use a very simple enum on our backend to represent the user logon type:
``` csharp
public enum UserLogonType
{
    Forms,
    Windows,
}
```
When we use the generated client to send the request it contains the following:
```
AccountType: "Models.Enums.UserLogonType'Windows'"
```
This causes the server to return a bad request as it can't parse the Enum.

If I modify the request and send this it works:
```
AccountType: "Windows"
```

I can also send the number and that will work too:
```
AccountType: 1
```
So I think there might be a problem with serialization?

**Comment by diegomvh** [comment]
Hi @ISimplifyComplexity 
Use `stringAsEnum` in the API configuración

https://github.com/diegomvh/AngularODataEntity/blob/89ee9bcecfdc3975282f8b334994b7342fc01ecd/src/app/app.module.ts#L52

Regards

**Comment by ISimplifyComplexity** [comment]
@diegomvh Thank you so much for the clear answer (it really couldn't have been much clearer). I got desperate and changed the generated client library to send a string but I just changed it back and this worked like a dream!
