### ISSUE TITLE
Collection contains

### ISSUE THREAD

**Issue by FacePalmDev** [diegomvh/angular-odata#24]
Hi, 

I'm trying to produce the following request (which works just fine). 

### Expected
```
https://localhost:1234/odata/users?$filter=Groups/any(group: group eq 'some-fancy-group-id')&$orderby=LogonName asc &$top=10&$count=true
```
The code I'm using is like this: 

``` typescript
    users
      .filter(oDataFilters)
      .skip($event.first)
      .top($event.rows)
      .orderBy(`${sortBy} ${sortDirection} `)
      .get({ withCount: true, withCredentials: true })
      .subscribe(
        ({ entities, meta }) => {
          this.recordCount = meta.count;
          this.items = entities;
          this.loading = false;
        },
        (err) => console.error(err));
```

The contents of the oDataFilters looks like this: 

``` typescript
{
  Groups:'some-fancy-group-id'
}

```

However I'm actually getting a request that looks like this: 
### Actual

```
https://localhost:1234/odata/users?$filter=Groups eq 'some-fancy-group-id'&$orderby=LogonName asc &$top=10&$count=true
```

Do you have any suggestions as to how I can produce the expected request above?

**Comment by diegomvh** [comment]
Hi @FacePalmDev 
For filtering please read the odata-query documentation 
I think ....
https://github.com/techniq/odata-query#implied-and
Internally the library use odata-query whit some customizations
Regards

**Comment by FacePalmDev** [comment]
@diegomvh Thank you! Looks really promising! I'll leave the ticket open for now but I will close it later once I've explored this and have something working! Thank you.

**Comment by FacePalmDev** [comment]
@diegomvh  It works 🙇🏽‍♂️🙏🏽. Thank you!!!
