### ISSUE TITLE
Can't bind an entity using ODataEntitySetResource<T>.entity( string | object )

### ISSUE THREAD

**Issue by AliAlmutawakel** [diegomvh/angular-odata#29]
I couldn't create a valid `EntityKey<T>` to target a single entity. I have a composite key for `T`
I'm trying the following
``` ts
// attempt 1 - fail (no qoutes)
let key = x.update.CustomerId + ',' + x.update.ItemId;
// attempt 2 - fail (escapeIllegalChars function)
let key = `'${x.update.CustomerId}','${x.update.ItemId}'`;
// attempt 3 - fail (entity-set.ts - never gets resolved because this.type() is always undefined and findStructuredTypeForType is never called which then this.schema?.resolveKey(key as {[name: string]: any}) is always undefined )
let key = { CustomerId: bagItem.CustomerId, ItemId: bagItem.ItemId };
let ent = itemOdata.entity(key);
let obs = ent.delete();
```
So what I'm guessing is, I HAVE to attach an entity schema config?

This is my import. I am passing the most minimum information. I do not want to maintain `entity.schema` files. 
```
ODataModule.forRoot({ serviceRootUrl: ENVIRONMENT.odataServiceRoot, metadataUrl: `${ENVIRONMENT.odataServiceRoot}/$metadata` } as ApiConfig),
```

@diegomvh what do you suggest?

**Comment by diegomvh** [comment]
Hi @AliAlmutawakel 
Is a Bug!!
The correct way is three.
But clearly there is a bug. Pretending to have an eschema is a problem that comes from my way of working with the library, I use the schema generator, but the idea is that the library works correctly even though there is no such schema.

Regards

**Comment by AliAlmutawakel** [comment]
I'd like to mention that after I generated the config and attached it. The result did not change. `this.type()` was still undefined.

Also, the $metadata Url is missing a `/` so my value comes up as `'https://localhost:5001/OData$metadata'`. I can fix it when I pass the service root with a `/` at the end but I think it might be necessary to check for that.
E.g. `url.replace(/\/$/, '') + '/';` to catch all.

**Comment by diegomvh** [comment]
Hi @AliAlmutawakel 
If you use the code generator don't need get service from factory. Just import the generated module in the main application module and include beside `ODataModule`. Then you can inject the generated services for your API.
In this version of the library try to make services have entity related names, `create`,` update`, `fetch`,` destroy` ... `assign` (I have doubts with this one)
While the resources are those that implement `post`,` get`, `delete` and verbs more linked to the http protocol
