### ISSUE TITLE
Update fails because URL is too long

### ISSUE THREAD

**Issue by DavidEgresits** [diegomvh/angular-odata#34]
Hi Diego,

I just tried out your OData project and it seems to be nice stuff, however, I faced with an issue:

During update I get an error:
![image](https://user-images.githubusercontent.com/15217061/123276899-e5aff980-d505-11eb-82c7-0ab581c507bf.png)

The generated URL is the following:
`https://services.odata.org/TripPinRESTierService/(S(qiryiepyqeb4vnqtrschujny))/People(UserName='elainestewart',FirstName='Elaine',LastName='Stewart',MiddleName=null,Gender='Female',Age=null,Emails=['Elaine@example.com','Elaine@contoso.com'],FavoriteFeature='Feature1',Features=[],AddressInfo=[Address='55%20Grizzly%20Peak%20Rd.',City=Name='Butte',CountryRegion='United%20States',Region='MT'],HomeAddress=null)`
Which indeed seems to be quite long. As of the OData spec, I would use a bit more compact one (which works well in a REST client, as only the UserName is Key according to the metadata):
`https://services.odata.org/TripPinRESTierService/(S(qiryiepyqeb4vnqtrschujny))/People('elainestewart')`

This gets generated from the following code
`this.peopleService.update(this.selectedPerson).subscribe(( entity ) => console.log("Updated: ", entity));` where selectedPerson is a complete person I got from the OData service.

Another interesting thing is that the update is a PUT request instead of the recommended (OData v4) PATCH.

Am I doing something wrong here? Could you please advise how can I use the update function correctly?
(Sidenote: get works, delete fails because of the same reason.)

Thanks and Best regards,
 David

**Comment by diegomvh** [comment]
hi David

I am reviewing the functionality of the services based on the problem you reported, there are several things to improve.
The library has to work with or without an associated schema; a vice of my way of working is neglecting the code when there is no schema ...
For example: when an update (PUT), an assign (PATCH) or a destroy (DELETE) is made ... if there is a schema, the key of the entity is resolved based on it ... and since in the case from your example the key is the UserName (but you shouldn't be using an associated schema right?)
After seeing the code ... I think it is very feasible to improve the services to work without a schema.

I see to solve it these days ...
There are other similar problems reported and even users asking for some documentation regarding the entity modification functions.

Thanks and regards
Diego

**Comment by DavidEgresits** [comment]
Hi Diego,

Thanks for the quick response, I saw that you already submitted a fix. Pretty fast! :)

To be honest, I'm not really sure how what you mean under using it with schema... I generated the OData classes with your ODataApiGen based on the metadata, so I assumed it is using the schema. What can I do to work with the schema?

Thanks and Best regards, 
   David

**Comment by diegomvh** [comment]
Hi David

Yes, by schema I mean the source code generated by ODataApiGen and include it in the main angular module as part of your project. In theory, if you insert the services generated from this module, they have a text string that defines the parser for the entity handled by the service.

In the example project there are several APIs included in the [main module](
https://github.com/diegomvh/AngularODataEntity/blob/main/src/app/app.module.ts) that exemplify this.

One thing does not imply the other :),
I think also the base services for entities needed some work, at least to remove the ambiguity between `entity` and `key`. 

Change their behavior by making the `update`, `patch` and `destroy` [signatures](https://github.com/diegomvh/angular-odata/blob/86d2416fa92fe1a04b3fa02229a62fa2c949f17a/projects/angular-odata/src/lib/services/entity-set.ts#L57) wait to receive the key and reserve for the  [save](https://github.com/diegomvh/angular-odata/blob/86d2416fa92fe1a04b3fa02229a62fa2c949f17a/projects/angular-odata/src/lib/services/entity-set.ts#L106) shortcut some of what I would expect to get if I have schema associated with the entity handled by the service.

These days I see how the library behaves with the project where it fulfills its function :)
And after being tested in production :O i release the new version.

Regards
