### ISSUE TITLE
get entity by guid

### ISSUE THREAD

**Issue by denissulea** [diegomvh/angular-odata#6]
It seems like it can't get an entity if its id is a guid.
this is the method definition in .net
[ODataRoute("({id})")]
public async Task<ActionResult<Info>> GetInfoAsync([FromODataUri]Guid id)

and this is the typescript code
let infoEntitiy = this.infos.entity(id);     where id is a string

so the generated request is this
http://localhost:59408/api/Infos('058be80c-c2f7-4a5d-bcd9-720d6f52212f')

How can i get rid of the quotes?

**Comment by diegomvh** [comment]
Hi @denissulea,
This issue was reported on #3 and is fixed on version 0.8.0 of the library
regards

PD: i will checked

**Comment by denissulea** [comment]
oh okay..unfortunately i have to use 0.7.0 as the project is using angular 7..do you know if there's a workaround?

**Comment by diegomvh** [comment]
Have you tried the latest version of a library in angular 7? Tell me if you have errors ... I use the latest version of angular, which I update on each release.
the code does not have a strong dependence on the angular version, if necessary, changing the code for different versions should not be complicated

**Comment by denissulea** [comment]
yes..below is the error..the project uses angular 7.3.9

ERROR in node_modules/angular-odata/lib/models/collection.d.ts(20,17): error TS2314: Generic type 'IteratorResult<T>' requires 1 type argument(s).
node_modules/angular-odata/lib/models/schema.d.ts(47,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/options.d.ts(71,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(9,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(10,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(17,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(18,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(22,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(27,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(28,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(29,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(30,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(31,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(32,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(33,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(34,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(35,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(36,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(41,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(42,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(43,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(44,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(45,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(46,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/segments.d.ts(43,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/segments.d.ts(44,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by diegomvh** [comment]
Angular 7 support
Challenge accepted!

**Comment by diegomvh** [comment]
Please @denissulea could you paste your packages.json file here?
Thanks

**Comment by denissulea** [comment]
> Angular 7 support
> Challenge accepted!
> TypeScript version?

v 3.2.4

**Comment by denissulea** [comment]
> Please @denissulea could you paste your package.json file here?
> Thanks

{
  "name": "Processor",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "build-lib": "ng build Processor-library",
    "packagr": "ng-packagr -p projects/Processor-library/ng-package.json"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/cdk": "~7.3.7",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/material": "~7.3.7",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@aspnet/signalr": "^1.1.4",
    "@ngneat/transloco": "^2.12.4",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "angular-odata": "^0.7.0",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "http-server": "^0.11.1",
    "jquery": "^3.3.1",
    "odata-query": "^5.7.0",
    "odata-query-builder": "0.0.7",
    "plotly.js": "^1.49.5",
    "rxjs": "~6.3.3",
    "scss-bundle": "^2.5.1",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.9",
    "@angular-devkit/build-ng-packagr": "^0.13.9",
    "@angular/cli": "^7.3.9",
    "@angular/compiler-cli": "^7.2.15",
    "@angular/language-service": "^7.2.15",
    "@ngx-formly/schematics": "^5.4.1",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^8.9.5",
    "@types/plotly.js": "^1.44.11",
    "codelyzer": "~4.5.0",
    "highlight-loader": "^0.7.3",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^4.2.0",
    "ng-swagger-gen": "^1.8.1",
    "prettier": "^1.18.2",
    "pretty-quick": "^1.11.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tsickle": "^0.35.0",
    "tslib": "^1.9.0",
    "tslint": "^5.20.0",
    "typescript": "^3.2.4"
  },
  "prettier": {
    "trailingComma": "es5",
    "tabWidth": 4,
    "semi": true,
    "singleQuote": true
  }
}

**Comment by denissulea** [comment]
yes..below is the error..the project uses angular 7.3.9

ERROR in node_modules/angular-odata/lib/models/collection.d.ts(20,17): error TS2314: Generic type 'IteratorResult<T>' requires 1 type argument(s).
node_modules/angular-odata/lib/models/schema.d.ts(47,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/options.d.ts(71,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(9,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(10,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(17,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(18,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(22,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(27,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(28,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(29,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(30,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(31,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(32,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(33,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(34,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(35,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(36,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(41,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(42,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(43,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(44,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(45,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/responses/annotations.d.ts(46,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/segments.d.ts(43,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-odata/lib/resources/segments.d.ts(44,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by diegomvh** [comment]
Hi @denissulea,
I create a new branch to build a version of the library for angular 7.
It is already published in npm.

```bash
npm install angular-odata@0.7.2
```

I hope this helps.
Thanks for giving the library a try.
regards

**Comment by denissulea** [comment]
Thanks..it works great now
