### ISSUE TITLE
Would like library replace single quote in Odata query by default

### ISSUE THREAD

**Issue by Ipri** [diegomvh/angular-odata#64]
Currently it known if in odata query is value with single quotes this will throw server error.  For Odata query all single quotes must be replaced with couple single quotes ( O'Reilly ->  O''Reilly ). Would like so this will be default behaviour in library query builder but not customer code.
![image](https://user-images.githubusercontent.com/7941315/185895964-ac803455-bd67-433e-bcd5-ff84c89cd005.png)

**Comment by diegomvh** [comment]
Hi @Ipri 
Thanks for your issue report.
Could you send me a code snippet that I can use to reproduce the quote escaping error?
