### ISSUE TITLE
how to /(S(juqvmnem2qpijynyewk4pld5))/People('russellwhyte')?$expand=Trips($top=2;$skip=1)

### ISSUE THREAD

**Issue by vigouredelaruse** [diegomvh/angular-odata#65]
i have an $expand query with multiple join clauses and i'd like to page through the expanded terms

my code is shaped as per below, and i'd like to be able to achieve the kind of query as per 
TripPinRESTierService/(S(juqvmnem2qpijynyewk4pld5))/People('russellwhyte')?$expand=Trips($top=2;$skip=1)

![image](https://user-images.githubusercontent.com/31052867/189395724-607c77e1-2c80-4d34-8ed0-50eacdcb426b.png)

please advise

**Comment by diegomvh** [comment]
Hi @vigouredelaruse 
Currently the library presents two ways of putting together queries.
One based on simple object-based syntax inspired by `odata-query`,
and the other using expressions inspired by `odata-filter-builder`
Both libraries are referenced for more help on how to do queries.
Likewise, the library extends these functions looking for a homogeneous behavior to perform everything that refers to queries, that is: I can use both styles of queries in all the functions that OData has (expand, filter, orderBy, select, etc)

The choice of one or the other is a matter of legibility.

I see that you use both in this query.
For the use of the expand in the form of an object, what you have to do in each internal object of the expand is to configure that expand with another object :) just need to add skip and top.

```ts
tenantEntities.query((q) => {
  //"About tastes there is nothing written", my grandfather used to say
  //This way is clearer for me the orderBy :) 
  q.orderBy([['CreatedAt', 'asc']]);
  q.expand({
    AccessControlEntries: { top: 10, skip: 10 },
    Owners: {},
    Accounts: {}
  });
  q.skip(offset);
  q.top(rowCount);
}
```

I leave some links to the `spec` where there are some simple but working examples of queries

[Object syntax](https://github.com/diegomvh/angular-odata/blob/603099cc4d410e5b8b36bacc2065d4989674395e/projects/angular-odata/src/lib/resources/query/builder.spec.ts#L1327)

[Expressions](https://github.com/diegomvh/angular-odata/blob/603099cc4d410e5b8b36bacc2065d4989674395e/projects/angular-odata/src/lib/resources/query/expressions/expand.spec.ts#L54)

best regards

**Comment by vigouredelaruse** [comment]
that looks very straightforward, i will apply the pattern. thanks for the links and the code and 'la sabiduria de tu abuelo'

best regards
