### ISSUE TITLE
how to access all properties in raw json reply

### ISSUE THREAD

**Issue by vigouredelaruse** [diegomvh/angular-odata#67]
given a json snippit like below that expands and counts a navigation property, created with a query like so
```
https://serviceroot.com/lache/ODataHosting/Tenant(ebc3f5cb-65df-4537-8279-08da9757ccd6)?$expand=AccessControlEntries($top=4;$skip=0;$count=true)
```

<img width="522" alt="image" src="https://user-images.githubusercontent.com/31052867/194185498-a790254c-9ed9-482d-98c2-67014a20032c.png">

if this were a $query against the root entityset the library lets you get the count from annots

but how do you get nested counts of navigation properties?, as in this case
```
AccessControlEntries@odata.count
```

as well and related, how does one access the raw json reply?

thanks

**Comment by vigouredelaruse** [comment]
thanks for looking into it

not to hijack the question but while on the subject of feature usage/request/buildout:
re entity relationship creation

what is, and where are any examples of the library's support for http methods patch, post and put, with the associated odata semantics pertaining to mutating entity relationships

as per
the aspnet odata docs [here](https://learn.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/entity-relations-in-odata-v4) claim the following

```
A reference has its own URI, with the form /Entity/NavigationProperty/$ref. 
For example, here is the URI to address the reference between a product and its supplier:

http:/host/Products(1)/Supplier/$ref
To add a relationship, the client sends a POST or PUT request to this address.

PUT if the navigation property is a single entity, such as Product.Supplier.
POST if the navigation property is a collection, such as Supplier.Products.
```

the payload is supposed to look like this
```
PUT http://myproductservice.example.com/Products(6)/Supplier/$ref HTTP/1.1
OData-Version: 4.0;NetFx
OData-MaxVersion: 4.0;NetFx
Accept: application/json;odata.metadata=minimal
Accept-Charset: UTF-8
Content-Type: application/json;odata.metadata=minimal
User-Agent: Microsoft ADO.NET Data Services
Host: myproductservice.example.com
Content-Length: 70
Expect: 100-continue

{"@odata.id":"http://myproductservice.example.com/Suppliers(4)"}
```

**Comment by diegomvh** [comment]
https://github.com/diegomvh/AngularODataEntity/blob/7859987680e3409bb606e969b1e0c2ac80b6d067/src/app/app.component.ts#L421

**Comment by vigouredelaruse** [comment]
```
    photoOfScott.reference().set(photo).subscribe(console.log); // Set is a shortcut for .put()
```

thanks again
