### ISSUE TITLE
Navigate to related entities

### ISSUE THREAD

**Issue by Ali-ModernBeauty** [diegomvh/angular-odata#7]
Hey Diego! Amazing work on the libraries!

Quick question. I am wondering if it's possible to translate this to code?

`http://services.odata.org/V4/TripPinService/People('russellwhyte')/Friends('scottketchum')/AddressInfo`

or minimum `http://services.odata.org/V4/TripPinService/People('russellwhyte')/Friends`

How can I only get a navigational property?

Here is my code for reference and what I tried so far.
```
  constructor(private _CONST : ConstantsService, odata: ODataClient) {
    this._customerOdata = odata.entitySet<Customer>(this._CONST.ODATA_URLS.CUSTOMERS);
  }

// fast forward to another function. This is where I was trying navigationProperty but got an error
let entity = this._customerOdata.entity(customer.Id);
let smth = await entity.navigationProperty<BagItem>("BagItems").all().toPromise();
```
The error was this:
![image](https://user-images.githubusercontent.com/38334720/76274828-536bdf80-6247-11ea-8f7f-a571cd7cd332.png)

Which in the library was (I think) in `entity.ts`
```
navigationProperty<N>(name: string) {
    return ODataNavigationPropertyResource.factory<N>(
      name,
      this.client, {
      segments: this.segments.clone(),
      options: this.options.clone(),
      parser: this.parser.parserFor<N>(name) //<-- right here. this.parser is null
    });
  }
```

BagItems is a navigational property of Customer. I'd like to only get the BagItems. You'd think expand would do it. You're right. However, looking at this piece of code:
```
// expanding and then selecting. Dirty hack to only get bagitems
let expand = {BagItems: {expand: "Item($expand=Prices($filter=PriceListCode eq 'MAIN'))" }};
let select = "BagItems";
```
I'm actually doing three nested expanding which is not allowed in dotnet core odata webapi. (max two)

P.S. I have an endpoint of `Customers({key})/BagItems` which returns all BagItems. So I'm trying to shortcut to get BagItems directly and avoid too many nested expands.

Let me know if you have any questions or demos that implement the Trippin example above. Much appreciated!

**Comment by diegomvh** [comment]
Hi @Ali-ModernBeauty 
Very good point!
I honestly put a lot of effort into building two products in parallel, the library and the [code generator](https://github.com/diegomvh/ODataApiGen). And on the way, without realizing it, there are these errors that arise from my rudimentary tests.
This is clearly a mistake, which needs to be fixed.
Here is an example of [TripPin](https://github.com/diegomvh/TripPinEntity) using the library and generator.

**Comment by diegomvh** [comment]
Thanks @Ali-ModernBeauty for giving a chance to the library and for your issue.
Commit 6372f58e3c62f96d1e61ce659ceb12b672102330 fix the bug

In the `expand` you can make use of the types, it is a feature recently added diegomvh/ODataApiGen#4 and #5 

Regards
