### ISSUE TITLE
Custom entity update endpoint address

### ISSUE THREAD

**Issue by SamShekhovtsov** [diegomvh/angular-odata#79]
Is this possible to add ability to specify a custom action address when updating entities? I think, that it would be really useful.

For example, there is an entity User I want to send a PUT request to change the user password. 

In that case, the request would look like:

```javascript
PUT /users -> to update the entire user entity
PUT users/passwordchange -> to change the password only
```

**Comment by diegomvh** [comment]
Hi @SamShekhovtsov 
I think for that kind of functionality the OData standard provides actions.
If you create an action bound to the user entity in the backend and then use the code generator, the action maps to a function in the generated angular services
