### ISSUE TITLE
Feature request: Simplify ODataSingeltonResource get options responseType to default to 'entity'

### ISSUE THREAD

**Issue by Ali-ModernBeauty** [diegomvh/angular-odata#8]
Hey! very minor issue. I hope I'm using the library correctly. It would be nice to have the `responseType` in `options` parameter of get in ODataSingletonResource to default to 'entity'

Here is some reference code:
```typescript
  private _user : AppUser;
  private _userOdata      : ODataSingletonResource<AppUser>;

  constructor(private _CONST  : ConstantsService,
                      odata   : ODataClient) {
    this._userOdata = odata.singleton<AppUser>(this._CONST.ODATA_URLS.USER);
  }

  public get user() : Promise<AppUser> {
    return new Promise(async (resolve)=>{
      if(!this._user)
        await this.initUser();
      resolve(this._user);
    });
  }

  async initUser(){
    // is this necessary? Singelton is implied that it returns one entity
    let options = {
      responseType: 'entity' as 'entity'
    }
    this._user = await this._userOdata.get(options).toPromise().then(([user]) => user);
  }
```

**Comment by diegomvh** [comment]
I think you are right, the main intention of the `OData<Thing>Resource` is to map the specifications of the standard.
For other uses the client can be used directly

```typescript
this.odata.get(this._userOdata).subscribe(body => { r.toEntities(body) });
```
Although for this the methods `toEntity`, `toEntities` and `toValue` would have to be public.

On the other hand, similar to what happens with the [functions](https://github.com/diegomvh/angular-odata/blob/e066aa76e43788b99c7a7ae61e110943385346bf/src/lib/resources/requests/function.ts#L68), it is not bad that the `responseTypes` are optional, what I do not know if it corresponds is to assume the value `entity` by default.

I'm going to make some changes and take a closer look at the standard's specifications.

Thank you
regards

**Comment by Ali-ModernBeauty** [comment]
I'll be more than happy to help any way I can.

**Comment by diegomvh** [comment]
Singlets work by default on a single entity

[Addressing Entities](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_AddressingEntities)
