### ISSUE TITLE
replacement of OdataEntityService.customCollectionAction in the latest version

### ISSUE THREAD

**Issue by VZhangTylerTech** [diegomvh/angular-odata#83]
Need to know what the alternative way for the now protected customCollectionAction method. The original call is listed below;     return this.customCollectionAction<AdministratableTenderType>(entityType, body,
      {
        returnType: "Tyler.Cashiering.Business.Administration.AdministratableTenderType",
        responseType: "entity"
      });
Please provide the conversion example.

**Comment by diegomvh** [comment]
Hi @VZhangTylerTech 

If you are using the code generator for each function/action, two functions are generated: one to create the resource and another to call the endpoint.

Here's an example of these two functions that were automatically generated in the `Caso` service of my application:

```ts
{
...
public crearIntervencionConRecursos(key: EntityKey<Caso>): ODataActionResource<{info: string, recursoIds: number[], requirenteIds: number[], expedienteId: number}, Intervencion> { 
  return this.entity(key).action<{info: string, recursoIds: number[], requirenteIds: number[], expedienteId: number}, Intervencion>('SIU.CrearIntervencionConRecursos');
}

public callCrearIntervencionConRecursos(key: EntityKey<Caso>, info: string, recursoIds: number[], requirenteIds: number[], expedienteId: number, options?: ODataActionOptions<Intervencion>) {
  return this.callAction<{info: string, recursoIds: number[], requirenteIds: number[], expedienteId: number}, Intervencion>(
      {info, recursoIds, requirenteIds, expedienteId}, 
      this.crearIntervencionConRecursos(key), 
      'entity', options) as Observable<ODataEntity<Intervencion>>;
}
...
}
```
