### ISSUE TITLE
How to perform deep filtering

### ISSUE THREAD

**Issue by CorneLosVisma** [diegomvh/angular-odata#84]
I just started using your library and I like it a lot.
Hope you can help me with this.

I am trying to do queries like this:

`https://services.odata.org/v4/TripPinService/People?$filter=Friends/any(a:a/FirstName%20eq%20%27Keith%27)&$expand=Friends`

So: "get all People that have a Friend with FirstName=='Keith'" 

Is this possible with your library?

**Comment by CorneLosVisma** [comment]
Ah wait, I think it is something like this:

```
people.query((q) => {
        q.filter({ Friends: { any: { Firstname: 'Keith' }}});
        q.expand('Friends');
    }
    .fetch()
    .subscribe();
```

Not sure it is the correct way but it seems to work.
However I do not like this syntax very much.

Something like this would be nice :-)

```
people
  .whereAny('Friends', friend => friend.equals('Firstname', 'Keith'))
  .expand('Friends')
  .fetch()
  .subscribe();
```

**Comment by diegomvh** [comment]
```ts
people.query((q) => {
        q.filter(({e, t}) => e().any(t.Friends, ({e, t}) => e().eq(t.Firstname, 'Keith')));
        q.expand(({e, t}) => e().field(t.Friends));
    }
    .fetch()
    .subscribe();
```
