### ISSUE TITLE
Http blob response type 

### ISSUE THREAD

**Issue by andrebbk** [diegomvh/angular-odata#92]
I can't consume an OData custom function that returns a filestream or simple a File/IFormFile

```
public callGetDocumentFile(documentId: string, options?: ODataFunctionOptions<FileStreamResult>) {
    return this.callFunction<{documentId: string}, FileStreamResult>(
      {documentId}, 
      this.getDocumentFile(), 
      'entity', options) as Observable<ODataEntity<FileStreamResult>>;
  }
```
  
 The getDocumentFile return the file as expected but the angular returns a parsed error, simply because it's not possible to specify the http response type as a 'blob'

**Comment by diegomvh** [comment]
Hello @andrebbk,
Was the code snippet presented generated with ODataApiGen?
In the project where I use the library, I created some functions that return files, and I defined them as follows:

```csharp
function = builder.EntityType<CasoPenal>()
                .Collection
            .Function("PrintCausas")
            .Returns<byte[]>();
function.Parameter<int>("principalId").Optional();
```

The result from ODataApiGen is:

```ts
public callPrintCausas(principalId?: number, options?: ODataOptions & {alias?: boolean}) {
    return this.callFunction<{principalId?: number}, ArrayBuffer>(
      {principalId}, 
      this.printCausas(), 
      'property', options) as Observable<ODataProperty<ArrayBuffer>>;
  }
```

By setting the return type as byte[], the generated function differs slightly.
It's unusual to set the return value as the entity FileStreamResult.
I hope this helps; if not, the other alternative is to not use the function and call it yourself, obtaining the resource perhaps like this:

```ts
<service>.getDocumentFile().callBlob({documentId}, options).subscribe(console.log);
```

Best of luck, and thank you for giving the library a chance!

**Comment by andrebbk** [comment]
I should have thanked you in advance!

That small detail in defining the OData function changed everything. It was enough to define the return type as byte[], to be able to fetch the blob from the angular side. It works like a charm!

The code is cleaner this way!
```
this.documentsService.getDocumentFile().callBlob({documentId: file.fileId})
      .subscribe({
        next: (blob) => {
          // Save the file and set the filename as needed
          saveAs(blob, file.fileName);
        },
        error: (error) => {
          console.log('Error getting document file as a blob with code {0}: {1}', file.fileId, error);
          this.loader.setLoading(false);
        },
        complete: () => this.loader.setLoading(false)      
      });
```

Thank you again for your help,
Wishing you all the best!
